"""remove_api_key_plaintext

Revision ID: 23c5d8198d8b
Revises: a0771308513b
Create Date: 2026-04-26 03:59:08.035013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23c5d8198d8b'
down_revision: Union[str, None] = 'a0771308513b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_control_units_api_key'), table_name='control_units')
    op.drop_column('control_units', 'api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('control_units', sa.Column('api_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_control_units_api_key'), 'control_units', ['api_key'], unique=True)
    # ### end Alembic commands ###
