"""initial_schema

Revision ID: a0771308513b
Revises: 
Create Date: 2026-04-25 00:03:51.452345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0771308513b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('power_status', sa.String(), nullable=True),
    sa.Column('sim_balance', sa.Float(), nullable=True),
    sa.Column('gsm_signal', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('dev_eui', sa.String(length=16), nullable=True),
    sa.Column('app_key', sa.String(length=32), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(length=64), nullable=False),
    sa.Column('api_key_hash', sa.String(length=255), nullable=False),
    sa.Column('registered_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['location_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_units_api_key'), 'control_units', ['api_key'], unique=True)
    op.create_index(op.f('ix_control_units_dev_eui'), 'control_units', ['dev_eui'], unique=True)
    op.create_index(op.f('ix_control_units_id'), 'control_units', ['id'], unique=False)
    op.create_index(op.f('ix_control_units_name'), 'control_units', ['name'], unique=False)
    op.create_index(op.f('ix_control_units_serial_number'), 'control_units', ['serial_number'], unique=True)
    op.create_table('monitored_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('temp_min', sa.Float(), nullable=False),
    sa.Column('temp_max', sa.Float(), nullable=False),
    sa.Column('hum_max', sa.Float(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitored_items_id'), 'monitored_items', ['id'], unique=False)
    op.add_column('sensors', sa.Column('control_unit_id', sa.Integer(), nullable=True))
    op.drop_index('ix_sensors_dev_eui', table_name='sensors')
    op.create_foreign_key(None, 'sensors', 'control_units', ['control_unit_id'], ['id'])
    op.drop_column('sensors', 'power_status')
    op.drop_column('sensors', 'battery_level')
    op.drop_column('sensors', 'gsm_signal')
    op.drop_column('sensors', 'app_key')
    op.drop_column('sensors', 'dev_eui')
    op.drop_column('sensors', 'sim_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensors', sa.Column('sim_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('sensors', sa.Column('dev_eui', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column('sensors', sa.Column('app_key', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.add_column('sensors', sa.Column('gsm_signal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sensors', sa.Column('battery_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sensors', sa.Column('power_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sensors', type_='foreignkey')
    op.create_index('ix_sensors_dev_eui', 'sensors', ['dev_eui'], unique=True)
    op.drop_column('sensors', 'control_unit_id')
    op.drop_index(op.f('ix_monitored_items_id'), table_name='monitored_items')
    op.drop_table('monitored_items')
    op.drop_index(op.f('ix_control_units_serial_number'), table_name='control_units')
    op.drop_index(op.f('ix_control_units_name'), table_name='control_units')
    op.drop_index(op.f('ix_control_units_id'), table_name='control_units')
    op.drop_index(op.f('ix_control_units_dev_eui'), table_name='control_units')
    op.drop_index(op.f('ix_control_units_api_key'), table_name='control_units')
    op.drop_table('control_units')
    # ### end Alembic commands ###
